apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.postgresql.fullnameOverride }}-certs
  labels:
    app: {{ .Values.postgresql.fullnameOverride }}
    chart: {{ .Values.postgresql.fullnameOverride }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ include "backstage.postgresql.gen-certs" . | indent 2 }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ .Values.postgresql.fullnameOverride }}-ca
  labels:
    app: {{ .Values.postgresql.fullnameOverride }}
    chart: {{ .Values.postgresql.fullnameOverride }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{ include "backstage.postgresql.gen-ca" . | indent 2 }}